- name: Install and configure software on Ubuntu server
  hosts: demo_server
  become: yes

  tasks:
    - name: Update & upgrade packages
      apt:
            update_cache: yes
            upgrade: dist

    - name: Install Docker
      apt:
          name:
          - docker.io
          - docker-compose
          state: present

    - name: Add user to Docker group
      user:
          name: "{{ ansible_user }}"
          groups: docker
          append: yes

    - name: Copy Docker Compose file to remote server
      copy:
          src: ./docker-compose.yml
          dest: "{{ ansible_env.HOME }}/docker-compose.yml"
          mode: '0644'

    - name: Start Docker Compose services
      command: docker-compose up -d
      args:
          chdir: "{{ ansible_env.HOME }}"

    - name: Open ports for external access
      ufw:
          rule: allow
          port: "{{ item }}"
          proto: tcp
      loop:
        - 80
        - 443
        - 3000
        - 5432
        - 9090
        - 8080
