---
- name: Install Zsh with color interface
  hosts: all
  become: yes

  tasks:
    - name: Install Zsh
      apt:
        name: zsh
        state: present

    - name: Install Oh My Zsh
      shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

    - name: Change default shell to Zsh
      user:
        name: "{{ ansible_user }}"
        shell: /bin/zsh

    - name: Set Zsh theme
      lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        line: 'ZSH_THEME="agnoster"'
        state: present

