- name: Install and configure software on Ubuntu server
  hosts: demo_server
  become: yes

  tasks:
    - name: Update & upgrade packages
      apt:
            update_cache: yes
            upgrade: dist

    - name: Install Docker
      apt:
          name:
          - docker.io
          - docker-compose
          state: present
      tags: install_docker

    - name: Add user to Docker group
      user:
          name: "{{ ansible_user }}"
          groups: docker
          append: yes
      tags: install_docker


    - name: Check if containers are running
      command: docker-compose ps --filter "status=running" --services
      register: containers_running

    - name: Stop containers if running
      command: docker-compose down
      args:
          chdir: /home/vps
      when: containers_running.stdout_lines | length > 0
      tags: install_softwares


    - name: Copy Docker Compose file to remote server
      copy:
          src: ./configs/docker-compose.yml
          dest: /home/vps/docker-compose.yml
          mode: '0644'
      tags: install_softwares

    - name: Copy Prometheus Config file to remote server
      copy:
          src: ./configs/prometheus.yml
          dest: /home/vps/prometheus.yml
          mode: '0644'
      tags: install_softwares

    - name: Start Docker Compose services
      command: docker-compose up -d
      args:
          chdir: /home/vps
      tags: install_softwares
    
    - name: Open ports if they are closed
      shell: "ufw status"
      register: ufw_status
      changed_when: false
      when: ansible_os_family == 'Debian'
      tags: check_ports

    - name: Open ports if they are closed
      ufw:
          state: enabled
          direction: incoming
          port: "{{ item }}"
      loop:
        - 8080
        - 9090
        - 5432
        - 3000
        - 443
        - 80
      when: "'Status: inactive' in ufw_status.stdout and loop.item not in ufw_status.stdout"
      tags: check_ports

