version: '3'

services:
#    gitlab:
#        image: gitlab/gitlab-ce:latest
#        container_name: gitlab
#        restart: always
#        hostname: gitlab.example.com
#        environment:
#            GITLAB_OMNIBUS_CONFIG: |
#                external_url 'http://gitlab.example.com'
#                nginx['listen_port'] = 80
#                nginx['listen_https'] = false
#                postgresql['enable'] = false
#                prometheus_monitoring['enable'] = false
#                grafana['enable'] = false
#        ports:
#            - "8080:80"
##            - "443:443"
#        volumes:
#            - "/srv/gitlab/config:/etc/gitlab"
#            - "/srv/gitlab/logs:/var/log/gitlab"
#            - "/srv/gitlab/data:/var/opt/gitlab"

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        restart: always
        ports:
            - "3000:3000"

    postgresql:
        image: postgres:latest
        container_name: postgresql
        restart: always
        environment:
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
            POSTGRES_DB: mydb
        volumes:
            - "/srv/postgresql/data:/var/lib/postgresql/data"

    nginx:
        image: nginx:latest
        container_name: nginx
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "/srv/nginx/logs:/var/log/nginx"
            - "/usr/share/nginx/html:/usr/share/nginx/html"


    prometheus:
        image: prom/prometheus
        container_name: prometheus
        restart: always
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml