global:
    scrape_interval: 15s
    evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
       - targets: ['localhost:9090']

  - job_name: 'gitlab'
    scrape_interval: 5s
    static_configs:
        - targets: ['my_app_host:8080']

  - job_name: 'nginx'
    static_configs:
        - targets: ['localhost:80']

  - job_name: 'postgresql'
    scrape_interval: 5s
    static_configs:
        - targets: ['my_database_host:5432']

remote_write:
    - url: "http://prometheus.example.com/write"

remote_read:
    - url: "http://prometheus.example.com/read"
