name: Ansible Playbook

on:
  push:
    branches:
      - main

env:
  ANSIBLE_VERSION: 2.9

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo apt-add-repository --yes --update ppa:ansible/ansible
        sudo apt-get install -y ansible-core
      env:
        ANSIBLE_VERSION: ${{ env.ANSIBLE_VERSION }}



    - name: Create SSH directory
      run: mkdir -p ~/.ssh

    - name: Add remote host key
      run: ssh-keyscan 185.209.162.241 >> ~/.ssh/known_hosts

    - name: Add SSH key
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Make SSH key executable
      run: chmod 70 ~/.ssh/id_rsa
    
    - name: Copy Inventory
      run: |
        echo [target_hosts] > inventory
        echo target_host ansible_connection=local >> inventory

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i hosts.ini docker_compose_install_to_server/install_tools_via_docker-compose.yml

